### ISSUE TITLE
More conversions

### ISSUE THREAD

**Issue by RicharddeCrep** [Paul-Reed/node-red-contrib-watt2kwh#1]
I suggest you add more conversions to the drop down box.

Cents/hr to $/Day   -   The required output is equivalent to the (Kilowatt conversion * 10 )

An alternative method is to add a Custom field that accepts a manually entered conversion factor.

I'd also suggest the generic name "Integrator" instead of Watt2kWh.   

Again, thanks for a good module.

**Comment by Paul-Reed** [comment]
Sorry for the delay, I missed the alert.
I would like to keep this node purely to calculate energy from power, and have no plans to expand it into a general conversion node, but thanks for the suggestion.
